import { useAppContext } from '../../../context/AppContext.jsx';
import './ActionQueuePanel.css';

function ActionQueuePanel() {
  const {
    audienceFilter,
    setAudienceFilter,
    loading,
    topActions,
    normalizePriority,
    runningAction,
    handleRunInsightAction,
    supportsAutomation,
    signalFiltersActive,
    signalFilterScopeLabel,
  } = useAppContext();

  return (
    <article className="panel action-panel action-queue-panel">
      <div className="section-head">
        <h2>Recommended Actions</h2>
        <div className="pill-row">
          <button
            className={audienceFilter === 'all' ? 'pill active' : 'pill'}
            onClick={() => setAudienceFilter('all')}
            type="button"
          >
            All
          </button>
          <button
            className={audienceFilter === 'manager' ? 'pill active' : 'pill'}
            onClick={() => setAudienceFilter('manager')}
            type="button"
          >
            Manager
          </button>
          <button
            className={audienceFilter === 'csm' ? 'pill active' : 'pill'}
            onClick={() => setAudienceFilter('csm')}
            type="button"
          >
            CSM
          </button>
        </div>
      </div>
      {signalFiltersActive && (
        <p className="filter-scope-note">
          Action queue is workspace-wide. Feed filters ({signalFilterScopeLabel}) only affect the Signal Feed.
        </p>
      )}

      {loading ? (
        <p>Loading recommended actions...</p>
      ) : topActions.length === 0 ? (
        <p>No actions yet. Sync integrations or add records.</p>
      ) : (
        <ul className="action-list">
          {topActions.map((insight) => (
            <li key={insight.category}>
              <div className="action-title-row">
                <h3>{insight.title}</h3>
                <span className={`priority ${normalizePriority(insight.priority)}`}>
                  {normalizePriority(insight.priority)}
                </span>
              </div>
              <p className="meta">
                {(insight.audience ?? 'manager').toUpperCase()}
                {insight.metric ? ` · ${insight.metric}` : ''}
                {' · '}
                {(insight.related_signal_ids ?? []).length} related signals
              </p>
              <p>{insight.recommendation}</p>
              {insight.rationale && <p className="insight-rationale">Why this matters: {insight.rationale}</p>}
              {(insight.evidence ?? []).length > 0 && (
                <ul className="evidence-list">
                  {insight.evidence.map((item, index) => (
                    <li key={`${insight.category}-evidence-${index}`}>{item}</li>
                  ))}
                </ul>
              )}
              <p className="meta">
                Suggested owner: {insight.owner_role ?? 'CS Operations'} · Due in{' '}
                {insight.due_in_days ?? 7} days · Confidence: {Math.round((insight.confidence ?? 0.7) * 100)}%
              </p>
              {(insight.generated_by || insight.confidence_explanation) && (
                <p className="meta insight-source">
                  Generated by: {insight.generated_by ?? 'rules'}
                  {insight.confidence_explanation
                    ? ` · Confidence basis: ${insight.confidence_explanation}`
                    : ''}
                </p>
              )}
              <div className="action-cta-row">
                <button
                  type="button"
                  onClick={() => handleRunInsightAction(insight)}
                  disabled={runningAction === insight.category || !supportsAutomation(insight.category)}
                >
                  {runningAction === insight.category
                    ? 'Running...'
                    : supportsAutomation(insight.category)
                      ? 'Apply This Action'
                      : 'Auto-Action Not Available'}
                </button>
              </div>
              {(insight.playbook_steps ?? []).length > 0 && (
                <ul className="playbook-list">
                  {insight.playbook_steps.map((step, index) => (
                    <li key={`${insight.category}-step-${index}`}>{step}</li>
                  ))}
                </ul>
              )}
            </li>
          ))}
        </ul>
      )}
    </article>
  );
}

export default ActionQueuePanel;
